
name: urwatul_wuthqa_v1
description: Urwatul Wuthqa - Full Flutter project (merged)
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  syncfusion_flutter_pdfviewer: ^20.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
    - assets/pdf/
