- name: Install dependencies
  run: flutter pub get
  working-directory: urwatul_wuthqa_v1

- name: Build APK
  run: flutter build apk --release
  working-directory: urwatul_wuthqa_v1

- name: Upload APK Artifact
  uses: actions/upload-artifact@v4
  with:
    name: release-apk
    path: urwatul_wuthqa_v1/build/app/outputs/flutter-apk/app-release.apk
